name: Build GitHub Pages

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          # only checkout the client folder
          sparse-checkout: client
          sparse-checkout-cone-mode: false

      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv client/* .
          rm -rf client
          ls -lah

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
        env:
          REACT_APP_API_ADDRESS: https://creator.cocktailberry.org
          PUBLIC_URL: https://andrewohnsland.github.io/
          REACT_APP_SHOWN_NAME: Andre Wohnsland
          REACT_APP_COPYRIGHT: A. Wohnsland
          OLD_API: https://awblog.deta.dev
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build